CREATE TABLE fornecedor(
	codigo_fornecedor BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL,
	cnpj VARCHAR(14) NOT NULL,
	cidade VARCHAR(50) NOT NULL,
	estado VARCHAR(2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;