CREATE TABLE usuario(
	codigo_usuario BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL,
	senha VARCHAR(15) NOT NULL,
	tipo_usuario VARCHAR(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;